config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: [:show]
  root 'articles#index'
  resources :articles do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 6 }
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order(created_at: :desc)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to action: :index
    else
      redirect_to action: :new
    end
  end

  def destroy
    article = Article.find(params[:id])
    if article.user_id == current_user.id
      article.destroy
      redirect_to action: :index
    else
      redirect_to action: :show
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    if article.user_id == current_user.id
      article.update(article_params)
      redirect_to action: :index
    else
      redirect_to action: :show
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def search
    @articles = Article.where('title LIKE(?)', "%#{params[:keyword]}%")
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to article_path(@comment.article)
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(article_id: params[:article_id], user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @articles = Article.order(created_at: :desc)
    super
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.haml
- @articles.each do |article|
  .article__item
    = link_to root_path, class: 'article__item__userimage' do
      = image_tag "", class: 'user__avater'
    .article__item__body
      = link_to article_path(article), class: 'article__item__body__title' do
        = article.title
      = link_to user_path(article.user), class: 'article__item__body__meta' do
        = article.user.nickname

app/views/articles/_search_article.html.haml
- @articles.each do |article|
  .search__article
    .search__article__left
      = link_to root_path, class: 'search__article__left__userlink' do
        = image_tag "", class: 'search__article__left__userlink__image'
    .search__article__main
      %h1.search__article__main__title
        = link_to article_path(article) do
          = article.title
        = link_to user_path(article.user), class: 'article__item__body__meta' do
          = article.user.nickname

app/views/articles/edit.html.haml
.allWrapper
  = render 'shared/header'
  .editor
    .editor__form
      = form_for @article do |f|
        .editor__content
          .editor__title
            = f.text_field :title, class: 'form__control', placeholder: 'タイトル'
          .editor__body
            .editor__body__text
              = f.text_area :text, class: 'editor__body__text__area', placeholder: 'プログラミング知識をMarkdown記法で書いて共有しよう'
        .editor__footer
          .editor__footer__save
            = f.label :image, class: 'image__picker' do
              = fa_icon 'picture-o'
              = f.file_field :image, class: 'footer__image'
            = f.submit 'Qiitaに投稿', class: 'editor__footer__save__submit'

app/views/articles/index.html.haml
.allWrapper
  = render 'shared/header'
  = render 'shared/main-contents'

app/views/articles/new.html.haml
.allWrapper
  = render 'shared/header'
  .editor
    .editor__form
      = form_for @article do |f|
        .editor__content
          .editor__title
            = f.text_field :title, class: 'form__control', placeholder: 'タイトル'
          .editor__body
            .editor__body__text
              = f.text_area :text, class: 'editor__body__text__area', placeholder: 'プログラミング知識をMarkdown記法で書いて共有しよう'
        .editor__footer
          .editor__footer__save
            = f.label :image, class: 'image__picker' do
              = fa_icon 'picture-o'
              = f.file_field :image, class: 'footer__image'
            = f.submit 'Qiitaに投稿', class: 'editor__footer__save__submit'

app/views/articles/search.html.haml
.allWrapper
  = render 'shared/header'
  .main__search
    .main__search__container
      = form_tag search_articles_path, method: :get do
        .main__search__container__form
          %button.search__btn{type: "submit"}
            %i.fa.fa-search
            検索
          .search__form
            %input.search__form__area{placeholder: "タイトルで検索", type: 'text', name: 'keyword'}
      .main__search__container__nav
        %ul.navigation__tabs
          %li.active
            = link_to "/", class: 'active__link' do
              すべて
              %span.article__count
                = @articles.length
          %li.active
            = link_to "/", class: 'active__stock' do
              ストック済み
              %span.stock__count
                = 0
        .sort__button
          = link_to "/", class: 'sort__button__link' do
            %span.btn
              %i.fa.fa-sort-amount-desc
              関連順
              %i.fa.fa-caret-down
      = render 'search_article'

app/views/articles/show.html.haml
.allWrapper
  = render 'shared/header'
  .main
    .container
      .article
        .article__header
          .article__header__info
            = link_to user_path(@article.user), class: 'article__header__info__name' do
              = @article.user.nickname
            .article__header__info__time
              = @article.created_at
            - if user_signed_in? && current_user.id == @article.user_id
              = link_to '削除', article_path, method: :delete
              = link_to '編集', edit_article_path, method: :get
          %h1.article__header__title
            = @article.title
        .article__body
          = simple_format(@article.text)
        = image_tag @article.image.url if @article.image.present?
      .comment
        = render @comment
      .comment__form
        .comment__form__header
          .comment__form__header__label
            コメントを投稿する
      = form_for [@article, @comment] do |f|
        .comment__form__body
          = f.text_area :content, placeholder: 'コメントを入力してください', class: 'form__control'
          = f.submit '投稿', class: 'send'

app/views/comments/_comment.html.haml
.posted__comment
  .comment__header
    .comment__header__creator
      - @comments.each do |comment|
        .comment__header__creator__info
          .comment__header__creator__info__username
            = comment.user.nickname
        .comment__text
          .comment__text__area
            = comment.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Qiita
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_header.html.haml
.header
  .header__contents
    .header__contents__left
      = link_to root_path, class: 'header__contents__left__logo' do
        %svg{viewbox: "0 0 75 25", xmlns: "http://www.w3.org/2000/svg"}
          %title Qiita
          %path{d: "M 24.6 12.2 C 24.6 6.2 20 0 12.2 0 C 6.2 0 0 4.6 0 12.4 c 0 6 4.6 12.2 12.4 12.2 c 2.5 0 5 -0.8 7.1 -2.3 l 3.6 3.6 l 1.6 -1.6 l -3.4 -3.4 c 2.1 -2.3 3.3 -5.3 3.3 -8.7 Z m -12.4 -10 c 5.7 0 10.2 4.4 10.2 10.1 c 0 4.9 -3.8 10.1 -10.1 10.1 s -10.1 -5.1 -10.1 -10 c 0 -6.4 5.1 -10.2 10 -10.2 Z M 30.5 7.1 h 2.1 v 17 h -2.1 Z M 31.5 4.8 c -1 0 -1.8 -0.8 -1.8 -1.8 s 0.8 -1.8 1.8 -1.8 s 1.8 0.8 1.8 1.8 s -0.8 1.8 -1.8 1.8 Z M 40 4.8 c -1 0 -1.8 -0.8 -1.8 -1.8 S 39 1.2 40 1.2 s 1.8 0.8 1.8 1.8 S 41 4.8 40 4.8 Z M 39 7.1 h 2.1 v 17 H 39 Z M 53.7 24.4 c -3.9 0 -6.2 -3 -6.2 -6 v -16 h 2.1 v 4.7 H 57 v 2.1 h -7.4 v 9.3 c 0 1.9 1.5 3.9 4.1 3.9 c 0.7 0 1.4 -0.2 2 -0.6 l 0.2 -0.1 l 1 1.8 l -0.2 0.1 c -0.9 0.5 -2 0.8 -3 0.8 Z M 67.6 24.5 c -5.7 0 -9.1 -4.5 -9.1 -8.9 c 0 -5.7 4.5 -9.1 8.9 -9.1 c 2.3 0 4.1 0.8 5.4 2.3 V 7.1 h 2.1 v 17 h -2.1 v -1.9 c -1.2 1.5 -3 2.3 -5.2 2.3 Z m -0.2 -15.9 c -3.4 0 -6.8 2.6 -6.8 7 c 0 3.4 2.6 6.8 7 6.8 c 2 0 4 -0.9 5.3 -2.5 v -8.8 c -1.4 -1.6 -3.3 -2.5 -5.5 -2.5 Z"}
      %div
        .header__contents__left__serector
          %span.fas.fa-caret-down
      - if user_signed_in?
        %div
          .header__contents__left__home
            ホーム
            %span.fas.fa-caret-down
      %div
        .header__contents__left__community
          コミュニティ
          %span.fas.fa-caret-down
      = form_tag search_articles_path, method: :get do
        .header__contents__left__search
          %span.fa.fa-search
          %input.header__contents__left__search__input{placeholder: "キーワードを入力", name: "keyword"}/
    .header__left__search__button
  .header__right
    - if user_signed_in?
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'header__right__stock'
      = link_to "ストック一覧", root_path, method: :get, class: 'header__right__stock fa fa-folder-open'
      = link_to "投稿する", new_article_path, method: :get, class: 'header__right__post fa fa-pencil-square-o'
      .notifications
        0
      = link_to user_path(current_user), class: 'login__user' do
        = image_tag '', class: 'avater'
        %span.fa.fa-fw.fa-caret-down
    - unless user_signed_in?
      = link_to "ユーザー登録", root_path, method: :get, class: 'header__right__signup'
      = link_to "ログイン", root_path, method: :get, class: 'header__right__login'

app/views/shared/_main-contents.html.haml
.home
  .home__contents
    .home__contents__menu
      = link_to "トレンド", root_path, method: :get, class: 'home__contents__menu__item fa fa-line-chart'
      = link_to "マイルストーン", root_path, method: :get, class: 'home__contents__menu__item2 fa fa-flag-checkered'
      - if user_signed_in?
        = link_to "タグフィード", root_path, method: :get, class: 'home__contents__menu__item2 fa fa-tags'
        = link_to "タイムライン", root_path, method: :get, class: 'home__contents__menu__item2 fa fa-list-ul'
    .home__contents__main
      .article
        .article__list__header
          .article__list__header__title
            .article__list__header__title__label
              %span.fa.fa-fw.fa-line-chart
              トレンド
            .article__list__header__title__sublabel
              最近人気の記事を毎日5時/17時に更新
          .article__list__header__itemlist__tab
            %span.article__list__header__itemlist__tab__item
              １日
            %span.article__list__header__itemlist__tab__item
              週間
            %span.article__list__header__itemlist__tab__item
              月間
        .article__list
          = render 'articles/article'

app/views/users/show.html.haml
.allWrapper
  = render 'shared/header'
  .main__container
    .user__profile
      .user__profile__avatar
        = image_tag "", class: 'user__profile__avatar__image'
      .user__profile__header
        %h3.user__profile__header__fullname
          = @user.nickname
        %h4.user__profile__header__name
          = "@sentral"
      .user__profile__info
        .user__profile__info__body__text
          = "駆け出しプログラマーです！まだアウトプットに慣れていないので変な記事も投稿してしまうかもしれませんが、もしお時間があれば見ていってください。またご指摘等もして頂けると嬉しいです。"
        .user__profile__info__body
          %i.fa.fa-building-o
          = "無所属"
        .user__profile__info__body
          %i.fa.fa-map-marker
          = "tokyo"
        %a.user__profile__info__body__edit
          %i.fa.fa-cog
          = "プロフィールを編集する"
      .user__profile__info
        .user__profile__info__heading
          = "フォロー中のタグ"
          %span.user__profile__count
            = link_to 1
        .user__profile__info__body
    .user__article
      .user__article__activity
        .user__article__activity__chart
        .user__article__activity__start
          %a.item
            %span.item__count
              = @articles.length
            %span.item__label
              = "Items"
          %a.contribution
            %span.contribution__count
              = 0
            %span.contribution__label
              = "Contribution"
          %a.followers
            %span.followers__count
              = 0
            %span.followers__label
              = "Followers"
        .user__local__nav
          %ul.nav__tabs
            %li.active
              %a.active__link
                = "最近の記事"
                %span.label__info
                  = @articles.length
            %li.presentation
              %a.tab__link
                = "いいねした記事"
            %li.presentation
              %a.tab__link
                = "限定共有記事"
            %li.presentation
              %a.tab__link
                = "コメント"
        .articles
          - @articles.each do |article|
            %article.article
              %a.article__image
                = image_tag ""
              .article__body
                .article__body__username
                  = link_to user_path(article.user) do
                    = article.user.nickname
                .article__body__title
                  = link_to article_path(article) do
                    = article.title